// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmstzq91y9UoJnqxr_TmIDwMm_H7hNB7o',
    appId: '1:444617849648:web:7115728517078dfb8d26f5',
    messagingSenderId: '444617849648',
    projectId: 'agriboost-5b19a',
    authDomain: 'agriboost-5b19a.firebaseapp.com',
    storageBucket: 'agriboost-5b19a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX1BlRIcrzC6KOU1D9-_CucJCPdvt2bRs',
    appId: '1:444617849648:android:1688fc58b84447c38d26f5',
    messagingSenderId: '444617849648',
    projectId: 'agriboost-5b19a',
    storageBucket: 'agriboost-5b19a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaWbDsLa9zLdmZajD4o157HYF52ygxB_k',
    appId: '1:444617849648:ios:3d6f58baacbfef2c8d26f5',
    messagingSenderId: '444617849648',
    projectId: 'agriboost-5b19a',
    storageBucket: 'agriboost-5b19a.firebasestorage.app',
    iosBundleId: 'com.example.agriboost',
  );
}
